version: '3'

services:
  es:
    build:
      context: .
      dockerfile: ./bin/Dockerfile
    image: x-elasticsearch-ik:8.12.2
    container_name: es
    restart: always
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    volumes:
      - ./bin/datas/es/:/usr/share/elasticsearch/data/
    entrypoint: >
      sh -c "echo -e '-*-\n-*-\n' | elasticsearch-keystore create &&
      bin/elasticsearch-plugin remove x-pack --purge &&
      bin/elasticsearch-keystore remove 'xpack.security.enabled' &&
      bin/elasticsearch-keystore remove 'xpack.security.authc.api_key.enabled' &&
      bin/elasticsearch-keystore remove 'xpack.encrypted.http.transport.key' &&
      bin/elasticsearch -Ehttp.cors.allow-origin=* -Ehttp.cors.enabled=true -Ehttp.cors.allow-methods=OPTIONS,HEAD,GET,POST,PUT,DELETE -Ehttp.cors.allow-headers=content-type"

  kibana:
    image: kibana:8.12.2
    restart: always
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200

  xblog:
    build: .
    restart: always
    command: bash -c 'sh /app/bin/docker_start.sh'
    ports:
      - "8000:8000"
    volumes:
      - ./collectedstatic:/app/collectedstatic
      - ./uploads:/app/uploads
    environment:
      - MYSQL_DATABASE=xblog
      - MYSQL_USER_NAME=root
      - MYSQL_PASSWORD=XBlOg!2!a@d#E
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - REDIS_URL=redis:6379
      - ELASTICSEARCH_HOST=es:9200
    links:
      - db
      - redis
    depends_on:
      - db
    container_name: xblog

