version: '3.8'

services:
  es:
    build:
      context: .
      dockerfile: ./bin/Dockerfile
    image: x-elasticsearch-ik:8.12.2
    container_name: es
    restart: always
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    volumes:
      - ./bin/datas/es/:/usr/share/elasticsearch/data/
      - /etc/elasticsearch/certs/http_ca.crt:/etc/elasticsearch/certs/http_ca.crt

  kibana:
    image: kibana:8.12.2
    restart: always
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=https://es:9200
