version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: xblog
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: XBlOg!2!a@d#E
    ports:
      - 3306:3306
    volumes:
      - ./bin/datas/mysql/:/var/lib/mysql
    depends_on:
      - redis
    container_name: db

  mysite:
    build: .
    restart: always
    command: bash -c 'sh /mysite/bin/docker_start.sh'
    ports:
      - "8000:8000"
    volumes:
      - .:/mysite
      - /var/www/static:/var/www/static
    environment:
      DJANGO_DEBUG: False
      MYSQL_DATABASE: xblog
      MYSQL_USER_NAME: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: XBlOg!2!a@d#E
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      REDIS_URL: redis:6379
    links:
      - db
      - redis
    depends_on:
      - db
    container_name: mysite

  nginx:
    restart: always
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./bin/nginx.conf:/etc/nginx/nginx.conf
      - /var/www/static:/var/www/static
    links:
      - mysite:mysite
    container_name: nginx

  redis:
    restart: always
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
