version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=xblog
      - MYSQL_ROOT_PASSWORD=XBlOg!2!a@d#E
    ports:
      - 3306:3306
    volumes:
      - ./bin/datas/mysql/:/var/lib/mysql
    depends_on:
      - redis
    container_name: db

  xblog:
    build: .
    restart: always
    command: bash -c 'sh /app/bin/docker_start.sh'
    ports:
      - "8000:8000"
    volumes:
      - ./collectedstatic:/app/collectedstatic
      - ./logs:/app/logs
      - ./media:/app/media
    environment:
      - MYSQL_DATABASE=djangoblog
      - MYSQL_USER_NAME=root
      - MYSQL_PASSWORD=XBlOg!2!a@d#E
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - REDIS_URL=redis:6379
    links:
      - db
      - redis
    depends_on:
      - db
    container_name: xblog
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./bin/nginx.conf:/etc/nginx/nginx.conf
      - ./collectedstatic:/app/collectedstatic
    links:
      - xblog:xblog
    container_name: nginx

  redis:
    restart: always
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
