# Generated by Django 5.0.2 on 2024-07-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients', models.CharField(max_length=300, verbose_name='收件人')),
                ('subject', models.CharField(max_length=2000, verbose_name='主题')),
                ('message', models.TextField(verbose_name='内容')),
                ('send_result', models.BooleanField(default=False, verbose_name='发送结果')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '邮件发送日志',
                'verbose_name_plural': '邮件发送日志',
                'ordering': ['-created_time'],
            },
        ),
    ]
