# Generated by Django 5.0.2 on 2024-07-28 10:11

import blog.models
import django.db.models.deletion
import mdeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='', max_length=200, verbose_name='网站名称')),
                ('site_description', models.TextField(default='', max_length=1000, verbose_name='网站描述')),
                ('site_seo_description', models.TextField(default='', max_length=1000, verbose_name='网站SEO描述')),
                ('site_keywords', models.TextField(default='', max_length=1000, verbose_name='网站关键字')),
                ('article_sub_length', models.IntegerField(default=300, verbose_name='文章摘要长度')),
                ('hot_article_count', models.IntegerField(default=7, verbose_name='首页热门文章数目')),
                ('comment_article_count', models.IntegerField(default=8, verbose_name='首页评论文章数目')),
                ('article_comment_count', models.IntegerField(default=5, verbose_name='文章页面默认显示评论数目')),
                ('show_google_adsense', models.BooleanField(default=False, verbose_name='是否显示谷歌广告')),
                ('google_adsense_codes', models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='广告内容')),
                ('open_site_comment', models.BooleanField(default=True, verbose_name='是否打开网站评论功能')),
                ('global_header', models.TextField(blank=True, default='', null=True, verbose_name='公共头部')),
                ('global_footer', models.TextField(blank=True, default='', null=True, verbose_name='公共尾部')),
                ('record_code', models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='备案号')),
                ('analytics_code', models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='网站统计代码')),
                ('show_police_code', models.BooleanField(default=False, verbose_name='是否显示公安备案号')),
                ('police_record_code', models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='公安备案号')),
                ('comment_need_review', models.BooleanField(default=False, verbose_name='评论是否需要审核')),
            ],
            options={
                'verbose_name': '网站配置',
                'verbose_name_plural': '网站配置',
            },
        ),
        migrations.CreateModel(
            name='ExtraSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('sequence', models.IntegerField(unique=True, verbose_name='排序')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '额外内容',
                'verbose_name_plural': '额外内容',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='链接名称')),
                ('link', models.URLField(verbose_name='链接地址')),
                ('master', models.CharField(max_length=50, verbose_name='站长')),
                ('email', models.EmailField(max_length=254, verbose_name='站长邮箱')),
                ('icon', models.URLField(blank=True, null=True, verbose_name='图标')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('notice', models.CharField(blank=True, max_length=30, null=True, verbose_name='提示')),
                ('sequence', models.IntegerField(unique=True, verbose_name='排序')),
                ('is_enable', models.BooleanField(default=False, verbose_name='是否显示')),
                ('show_type', models.CharField(choices=[('home', '首页'), ('list', '列表页'), ('page', '文章页面'), ('all', '全站'), ('blog_roll', '友情链接页面')], default='home', max_length=9, verbose_name='显示类型')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='图标')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='标签名')),
                ('slug', models.SlugField(blank=True, default='no-slug', max_length=60, verbose_name='处理后的标题')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='图标')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='分类名')),
                ('slug', models.SlugField(blank=True, default='no-slug', max_length=60, verbose_name='处理后的标题')),
                ('index', models.IntegerField(default=0, verbose_name='权重排序-越大越靠前')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='父级分类')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['-index'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='标题')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='处理后的标题')),
                ('icon', models.CharField(blank=True, max_length=200, null=True, verbose_name='图标')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=blog.models.author_directory_path, verbose_name='封面')),
                ('body', mdeditor.fields.MDTextField(verbose_name='正文')),
                ('show_toc', models.BooleanField(default=False, verbose_name='是否显示toc目录')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('article_order', models.IntegerField(default=0, verbose_name='排序,数字越大越靠前')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('publish', '发表')], default='draft', max_length=20, verbose_name='文章状态')),
                ('comment_status', models.CharField(choices=[('open', '打开'), ('close', '关闭')], default='open', max_length=20, verbose_name='评论状态')),
                ('type', models.CharField(choices=[('article', '文章'), ('page', '页面')], default='article', max_length=20, verbose_name='类型')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='分类')),
                ('tags', models.ManyToManyField(blank=True, to='blog.tag', verbose_name='标签集合')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-article_order', '-created_time'],
                'get_latest_by': 'id',
            },
        ),
    ]
